[package]
name = "tokenomics"
version = "1.0.0"
authors = []

[addresses]
dxlyn = "0xe937e73b679cfda8acba050b8c364b598861e1a0e92bef13b6d60461ec37ad26"
FACoin = "0x2"
dev ="0xe937e73b679cfda8acba050b8c364b598861e1a0e92bef13b6d60461ec37ad26"

[dev-addresses]

[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = 'aptosvm-v1.16_supra-v0.4.0'

[dev-dependencies]
